let currentPlayer = null;
let scoutMode = false;
let typingTimeouts = []; // 🔥 agregado
let ratingsPage = 0;
let currentColIndex = 0;
let currentRowIndex = 0;

const SCOUT_DATA = {
  "RICHIE SAUNDERS": `
    <h3>SCOUTING REPORT</h3>
    <p>. BUENA ALTURA Y CAPACIDAD ATLETICA</p>
    <p>. MAESTRO DEL CATCH AND SHOOT</p>
    <p>. 44.8 3P% DESDE LAS ESQUINAS</p>
    <p>. BUEN JUEGO SIN BALON Y EN FASTBREAK</p>
    <p>. BUEN DEFINIDOR: 64.8% EN LA PINTURA</p>
    <p>. JUEGA CON ENERGIA EN AMBOS COSTADOS</p>
    <p>. BUEN APORTE EN REBOTES</p>
    <p>. POCA CREACION CON EL BALON O PASE</p>
    <p>. GRAVE LESION DE RODILLA</p>
    <p>. PROYECTO "VETERANO" -24 AÑOS-</p>
    <p>. VALOR: 2° RONDA</p>
  `,
  "default": `
    <h3>SCOUT REPORT</h3>
    <p>SCOUT NO DISPONIBLE</p>
  `,

  "AJ DYBANTSA": `
    <h3>SCOUTING REPORT</h3>
    <p>. ALTURA Y CAPACIDAD ATLETICA ELITE</p>
    <p>. ENORMES RECURSOS ANOTADORES</p>
    <p>. MANEJO + EXPLOSION + AGRESIVIDAD</p>
    <p>. EXCELENTE TIRO A MEDIA DISTANCIA</p>
    <p>. VIVE CERCA DEL ARO Y EN LA LINEA</p>
    <p>. TOQUE DUDOSO Y MAL TRIPLERO</p>
    <p>. TIENE DESTELLOS DE BUEN PASADOR</p>
    <p>. DEFENSA IRREGULAR CON DISTRACCIONES</p>
    <p>. MUY BUEN REBOTERO EN EL ARO PROPIO</p>
    <p>. CONDICIONES PARA BRILLAR EN DEFENSA</p>
    <p>. VALOR: PRIMER PICK DEL DRAFT</p>
  `,

  "ADAY MARA": `
    <h3>SCOUTING REPORT</h3>
    <p>. ALTURA IDEAL Y BUEN FISICO</p>
    <p>. ALGO LENTO DE MOVIMIENTOS</p>
    <p>. GRANDES RECURSOS PARA SU TAMAÑO</p>
    <p>. DEFINIDOR LETAL; TOQUE + ALTURA</p>
    <p>. MUY BUEN PASADOR; GRAN VISION</p>
    <p>. TODAVIA SIN TIRO MAS ALLA DE 3 MTS.</p>
    <p>. MAL TIRADOR DE LIBRES</p>
    <p>. PROTECTOR DE ARO; TAPAS + PRESENCIA</p>
    <p>. NO ES EL REBOTERO MAS SEGURO</p>
    <p>. DUDAS DE CARA A LA VELOCIDAD NBA</p>
    <p>. VALOR: PICK DE LOTERIA</p>
  `,

  "MJ COLLINS": `
    <h3>SCOUTING REPORT</h3>
    <p>. ALTURA DE BASE, JUEGO DE ESCOLTA</p>
    <p>. BUEN ATLETA; MUCHO SALTO, RAPIDO</p>
    <p>. BUENA 25-26 DE TRES: 36% EN +6 3PA</p>
    <p>. TRES AÑOS PREVIOS: 28% EN 3P</p>
    <p>. BUEN TIRO DE MEDIA DISTANCIA</p>
    <p>. PELIGROSO EN TRANSICION, EXPLOSIVO</p>
    <p>. SIN BUENA CREACION, DRIBLE O PASE</p>
    <p>. PRESIONA EN DEFENSA; VELOZ, INTENSO</p>
    <p>. LIMITADO POR FALTA DE ALTURA/PESO</p>
    <p>. POCO REBOTE O ROBOS</p>
    <p>. VALOR: UNDRAFTED</p>
  `,

  "MELVIN COUNCIL": `
    <h3>SCOUTING REPORT</h3>
    <p>. BUENA ALTURA, LARGO; FALTAN KG</p>
    <p>. EXTREMADAMENTE VELOZ</p>
    <p>. BASE MUY AGRESIVO PARA PENETRAR</p>
    <p>. PRIMER PASO DESTRUCTIVO</p>
    <p>. DEFINIDOR IRREGULAR; ATOLONDRADO</p>
    <p>. BUEN USO DE LA FLOTADORA</p>
    <p>. NO ES UN BUEN TIRADOR DE TRES</p>
    <p>. NO SOBRESALE COMO PASADOR</p>
    <p>. DEFENSOR ATACABLE POR FALTA DE KG</p>
    <p>. AYUDA CON REBOTES DEFENSIVOS</p>
    <p>. VALOR: UNDRAFTED</p>
  `,

  "LAMAR WILKERSON": `
    <h3>SCOUTING REPORT</h3>
    <p>. SIN GRAN ALTURA PARA ESCOLTA</p>
    <p>. NO SOBRESALE DESDE LO ATLETICO</p>
    <p>. ESPECIALSITA TRIPLERO</p>
    <p>. 41% DE TRES EN LOS ULTIMOS DOS AÑOS</p>
    <p>. BUENA MECANICA; ALCANCE NBA</p>
    <p>. CERCA DEL 90% EN TIROS LIBRES</p>
    <p>. SIN TANTA CREACION DESDE EL DRIBLE</p>
    <p>. CORRECTO PASADOR; CUMPLE SU ROL</p>
    <p>. BUEN ESFUERZO DEFENSIVO; ATENTO</p>
    <p>. LIMITADO POR FISICO/CAP. ATLETICA</p>
    <p>. VALOR: 2°RONDA/UNDRAFTED</p>
  `,

  "CHRIS BELL": `
    <h3>SCOUTING REPORT</h3>
    <p>. MUY BUENA ALTURA PARA 3</p>
    <p>. MALO DESSDE LO ATLETICO; LIVIANO</p>
    <p>. ESPECIALSITA TRIPLERO</p>
    <p>. 40% EN 3P EN MUCHOS INTENTOS</p>
    <p>. ARRIBA DEL 85% EN TIROS LIBRES</p>
    <p>. SIN CREACION DESDE EL DRIBLE</p>
    <p>. NO PASA EL BALON; ROL LIMITADO</p>
    <p>. MALA DEFENSA; SIN POTENCIA FISICA</p>
    <p>. REBOTEA AL RITMO DE UN BASE</p>
    <p>. POCOS ROBOS; 100% ATACABLE</p>
    <p>. VALOR: UNDRAFTED</p>
  `,

  "TUCKER DEVRIES": `
    <h3>SCOUTING REPORT</h3>
    <p>. MUY BUEN FISICO PARA 3</p>
    <p>. SIN CAPACIDAD ATLETICA NBA</p>
    <p>. MUY BUEN TIRADOR DE TRES PUNTOS</p>
    <p>. 33% 3P EN LA 2025-2026</p>
    <p>. 37% 3P EN LOS 4 AÑOS PREVIOS</p>
    <p>. BUENA MECANICA Y TIRO DE MEDIA</p>
    <p>. 85% EN TIROS LIBRES</p>
    <p>. BUEN PASADOR; NO PENETRA</p>
    <p>. TIENE FISICO Y AYUDA EN EL REBOTE</p>
    <p>. SIN VELOCIDAD PARA DEFENSA NBA</p>
    <p>. VALOR: 2°RONDA/UNDRAFTED</p>
  `,

  "NATHAN BITTLE": `
    <h3>SCOUTING REPORT</h3>
    <p>. GRAN ALTURA; BRAZOS MUY LARGOS</p>
    <p>. SIN CAPACIDAD ATLETICA NBA</p>
    <p>. BUEN TIRADOR PARA SU TAMAÑO</p>
    <p>. 33% 3P EN SU CARRERA NCAA</p>
    <p>. MEJOR EN EL POP QUE EN EL ROLL</p>
    <p>. DEFINIDOR DE TOQUE; SIN EXPLOSION</p>
    <p>. BUEN PASADOR; TIENE TALENTO</p>
    <p>. SIN VELOCIDAD NBA PARA DEFENDER</p>
    <p>. POR DEBAJO DE LA MEDIA EN EL REBOTE</p>
    <p>. SUMA TAPONES POR ALTO/LARGO</p>
    <p>. VALOR: UNDRAFTED</p>
  `,

  "XAIVIAN LEE": `
    <h3>SCOUTING REPORT</h3>
    <p>. BUENA ALTURA; NO MUY POTENTE</p>
    <p>. BUEN ATLETA: RAPIDO, INTENSO</p>
    <p>. IRREGULAR TIRADOR DE TRES</p>
    <p>. 29% DE TRES (25-26); 32% (CARRERA)</p>
    <p>. SIN BUEN JUEGO DE MEDIA</p>
    <p>. VELOZ PARA ATACAR; BUEN DEFINIDOR</p>
    <p>. PELIGROSO A CAMPO ABIERTO</p>
    <p>. SOLIDO PASADOR; POCAS PERDIDAS</p>
    <p>. DEFIENDE CON ENERGIA; VA AL REBOTE</p>
    <p>. LIMITADO POR FALTA DE FISICO</p>
    <p>. VALOR: UNDRAFTED</p>
  `,

  "TRE DONALDSON": `
    <h3>SCOUTING REPORT</h3>
    <p>. SIN GRAN ALTURA; FUERTE FISICAMENTE</p>
    <p>. BUEN ATLETA; VELOZ, VERTICAL</p>
    <p>. TIRADOR CORRECTO, NO ESPECIALISTA</p>
    <p>. 38% EN 3P EN SU CARRERA DE 4 AÑOS</p>
    <p>. AGRESIVO PARA PENETRAR; FUERTE</p>
    <p>. NO ES EL DEFINIDOR MAS SEGURO</p>
    <p>. APENAS SUPERA EL 70% EN LIBRES</p>
    <p>. SIN GRAN TALENTO PASADOR O DRIBLE</p>
    <p>. DEFENSOR FISICO PERO SIN ESTATURA</p>
    <p>. AYUDA EN EL REBOTE DEFENSIVO</p>
    <p>. VALOR: UNDRAFTED</p>
  `,

  "AIDAN MAHANEY": `
    <h3>SCOUTING REPORT</h3>
    <p>. CORRECTA ALTURA PARA BASE</p>
    <p>. SIN CAPACIDAD ATLETICA NBA</p>
    <p>. MAS 1-2 QUE BASE PURO</p>
    <p>. BUEN TIRADOR DE TRES PUNTOS</p>
    <p>. ANOTA DESDE DRIBLE EN MEDIA Y LARGA</p>
    <p>. SIN FISICO PARA LA PINTURA</p>
    <p>. NO DESTACA COMO PASADOR</p>
    <p>. EL PEOR DEFENSOR DEL DRAFT</p>
    <p>. NO SUMA ROBOS NI BAJA REBOTES</p>
    <p>. ATACABLE INCLUSO EN LA NCAA</p>
    <p>. VALOR: UNDRAFTED</p>
  `,

  "GRAHAM IKE": `
    <h3>SCOUTING REPORT</h3>
    <p>. BUENA ALTURA; BRAZOS MUY LARGOS</p>
    <p>. FUERTE PERO NO ES UN ATLETA NBA</p>
    <p>. INTERIOR ANOTADOR OLD-SCHOOL</p>
    <p>. COMBINA FISICO Y MUY BUEN TOQUE</p>
    <p>. GRAN DEFINIDOR EN PICK AND ROLL</p>
    <p>. BUEN TIRO DE MEDIA Y ALGO DE TRES</p>
    <p>. BUEN PASADOR; CREA CON LA BOLA</p>
    <p>. MANOS SUMAMENTE SEGURAS</p>
    <p>. BUEN REBOTERO; NO DA TAPONES</p>
    <p>. MAL DEFENSOR; SIN VELOCIDAD/SALTO</p>
    <p>. VALOR: UNDRAFTED</p>
  `,

  "MICHAEL AJAYI": `
    <h3>SCOUTING REPORT</h3>
    <p>. SIN GRAN ALTURA PARA 3/4</p>
    <p>. BRAZOS MUY LARGOS; BUEN ATLETA</p>
    <p>. LIMITADO COMO ANOTADOR</p>
    <p>. MAL TIRADOR; SIN BUENA MECANICA</p>
    <p>. 26% EN TRIPLES Y 65% EN LIBRES</p>
    <p>. MAS POTENTE QUE HABIL PARA CREAR</p>
    <p>. NO SOBRESALE COMO PASADOR</p>
    <p>. ESPECIALSITA DEFENSIVO</p>
    <p>. DEFIENDE DESDE BASES HASTA PIVOTS</p>
    <p>. REBOTEA COMO UN PIVOT; DA TAPAS</p>
    <p>. VALOR: UNDRAFTED</p>
  `,

  "BOOPIE MILLER": `
    <h3>SCOUTING REPORT</h3>
    <p>. MUY BAJO Y LIVIANO; BRAZOS CORTOS</p>
    <p>. MAS VELOZ QUE EXPLOSIVO</p>
    <p>. BASE PURO, TALENTOSO</p>
    <p>. CORRECTO TRIPLERO: 38% EN 5 AÑOS</p>
    <p>. MAS SEGURO EN LA MEDIA DISTANCIA</p>
    <p>. GRAN MANEJO Y TIRO DESDE EL DRIBLE</p>
    <p>. MUY BUEN PASADOR; CREATIVO</p>
    <p>. JUGADOR DE PICK AND ROLL</p>
    <p>. VULNERABLE EN DEFENSA POR FISICO</p>
    <p>. VA AL REBOTE Y RECUPERA BALONES</p>
    <p>. VALOR: UNDRAFTED</p>
  `,

  "SETH TRIMBLE": `
    <h3>SCOUTING REPORT</h3>
    <p>. BAJO PERO CON BRAZOS LARGOS</p>
    <p>. FENOMENAL CAPACIDAD ATLETICA</p>
    <p>. ALTURA DE BASE PERO JUGABA DE 2</p>
    <p>. MAL TIRADOR DE TRES: 29% EN 4 AÑOS</p>
    <p>. UN RAYO EN TRANSICION</p>
    <p>. ATACA POR VELOCIDAD Y EXPLOSION</p>
    <p>. APORTA POCO COMO PASADOR</p>
    <p>. DEFENSOR MUY INTENSO; ENERGIA</p>
    <p>. MUY VELOZ PARA LAS AYUDAS</p>
    <p>. BUENA DEFENSA DE 1 VS. 1</p>
    <p>. VALOR: 2° RONDA/UNDRAFTED</p>
  `,

  "JARON PIERRE": `
    <h3>SCOUTING REPORT</h3>
    <p>. SOLIDA ALTURA Y CAPACIDAD ATLETICA</p>
    <p>. IMPORTANTE TALENTO ANOTADOR</p>
    <p>. BUEN TIRADOR; MUCHOS INTENTOS, 37%</p>
    <p>. TIRA DESDE DRIBLE EN MEDIA O LARGA</p>
    <p>. BUEN MANEJO, COMODO CON LA BOLA</p>
    <p>. ATACA; PELIGROSO EN TRANSICION</p>
    <p>. ALGO EGOISTA, FRENA LA BOLA</p>
    <p>. NO ES UN DEFENSOR/JUGADOR FISICO</p>
    <p>. TIENE DISTRACCIONES EN DEFENSA</p>
    <p>. BUEN REBOTERO PARA SU POSICION</p>
    <p>. VALOR: UNDRAFTED</p>
  `,

  "MARKHI STRICKLAND": `
    <h3>SCOUTING REPORT</h3>
    <p>. 3-4 SIN GRAN ALTURA; FUERTE, LARGO</p>
    <p>. APENAS PROMEDIO COMO ATLETA</p>
    <p>. SIN TIRO EXTERIOR; 0 3P EN LA 25-26</p>
    <p>. POR DEBAJO DEL 50% EN TIROS LIBRES</p>
    <p>. NO CREA CON LA BOLA</p>
    <p>. PTS = CORTES, REBOTES O TRANSICION</p>
    <p>. CORRECTO DEFENSOR; FISICO</p>
    <p>. MUY MAL REBOTERO EN DEFENSA</p>
    <p>. JUGABA DE INTERIOR EN NORTH DAKOTA</p>
    <p>. VERSION EMPEORADA DE SU PADRE MARK</p>
    <p>. VALOR: UNDRAFTED</p>
  `,

  "JAXON KOHLER": `
    <h3>SCOUTING REPORT</h3>
    <p>. SIN GRAN ESTATURA; BRAZOS CORTOS</p>
    <p>. FUERTE PERO MUY POCO ATLETICO</p>
    <p>. CONVERTIDO EN ESPECIALISTA TRIPLERO</p>
    <p>. 39% EN MAS DE 4 3PA EN LA 2025-26</p>
    <p>. EXCELENTE 87% EN TIROS LIBRES</p>
    <p>. BUEN PASADOR DESDE POSTE ALTO</p>
    <p>. SIN TECNICA/RAPIDEZ PARA CREAR</p>
    <p>. MUY FISICO PERO LIMITADO EN DEFENSA</p>
    <p>. SIN VELOCIDAD NBA; NO DA TAPONES</p>
    <p>. GRAN REBOTERO EN AMBAS PINTURAS</p>
    <p>. VALOR: UNDRAFTED</p>
  `,

  "JAYLIN SELLERS": `
    <h3>SCOUTING REPORT</h3>
    <p>. ALTURA DE BASE, JUEGO DE ESCOLTA</p>
    <p>. BUEN ATLETA, RAPIDO, VERTICAL</p>
    <p>. ANOTADOR PURO; TALENTO CREADOR</p>
    <p>. 43% EN +5 TRIPLES EN LA 2025-26</p>
    <p>. +40% 3P EN TRES DE CUATRO AÑOS NCAA </p>
    <p>. BUEN TIRO EN MOVIMIENTO</p>
    <p>. MUY BUEN 1 VS. 1; ATACA Y DEFINE</p>
    <p>. ARRIBA DEL 85% EN TIROS LIBRES</p>
    <p>. SOLO MIRA EL ARO; MUY POCO PASE</p>
    <p>. MAL DEFENSOR; LIVIANO Y BAJO</p>
    <p>. VALOR: 2° RONDA/UNDRAFTED</p>
  `,

  "DUKE MILES": `
    <h3>SCOUTING REPORT</h3>
    <p>. BASE BAJO Y NO MUY ATLETICO</p>
    <p>. APENAS PROMEDIO COMO TRIPLERO</p>
    <p>. 35% EN 3P EN SUS 5 AÑOS EN LA NCAA</p>
    <p>. MUY AGRESIVO PARA PENETRAR</p>
    <p>. GANA FALTAS Y 90% EN LIBRES </p>
    <p>. NO TENDRIA ESE ROL EN LA NBA</p>
    <p>. SOLIDO PASADOR, SIN GRAN BRILLO</p>
    <p>. PESTE DEFENSIVA; PRESIONA</p>
    <p>. LIDERO SEC CON 2.6 ROBOS</p>
    <p>. AYUDA EN EL REBOTE DEFENSIVO</p>
    <p>. VALOR: UNDRAFTED</p>
  `,

  "KASEN JENNINGS": `
    <h3>SCOUTING REPORT</h3>
    <p>. BUENA ALTURA PARA 1; BRAZOS LARGOS</p>
    <p>. SOLIDA CAPACIDAD ATLETICA Y FISICO</p>
    <p>. TAMAÑO DE BASE, JUEGO DE ESCOLTA</p>
    <p>. TRIPLERO IRREGULAR: 34% EN 5 AÑOS</p>
    <p>. ATACA PERO NO ES UN GRAN DEFINIDOR</p>
    <p>. MUY POCA ORGANIZACION O PASE</p>
    <p>. UN SOLO AÑO CON +7 PTS/PJ</p>
    <p>. DESTACABA EN CONFERENCIA PEQUEÑA</p>
    <p>. BUENAS HERRAMIENTAS DEFENSIVAS</p>
    <p>. AYUDA EN EL REBOTE DEFENSIVO</p>
    <p>. VALOR: UNDRAFTED</p>
  `,

  "PETER SUDER": `
    <h3>SCOUTING REPORT</h3>
    <p>. BUENA ALTURA PARA 1-2; FUERTE</p>
    <p>. SIN CAPACIDAD ATLETICA NBA</p>
    <p>. NO ES UN BUEN TRIPLERO</p>
    <p>. 42% 3P EN POCOS INTENTOS EN 25-26</p>
    <p>. 30% 3P EN LOS TRES AÑOS PREVIOS</p>
    <p>. POR DEBAJO DEL 75% EN TIROS LIBRES</p>
    <p>. BUENA MEDIA Y ATACA EL ARO; 60% 2P</p>
    <p>. CREA PERO NO ES UN BASE PURO</p>
    <p>. SUMA REBOTES, ROBOS Y TAPONES</p>
    <p>. LA FALTA DE EXPLOSION LO LIMITA</p>
    <p>. VALOR: UNDRAFTED</p>
  `,

  "JAMAL FULLER": `
    <h3>SCOUTING REPORT</h3>
    <p>. 3-4 CON ALTURA DE BASE</p>
    <p>. NO SOBRESALE DESDE LO ATLETICO</p>
    <p>. 40% 3P EN DOS AÑOS EN LA NCAA</p>
    <p>. SIN TALENTO CON LA BOLA</p>
    <p>. POCO COMO PASADOR/CREADOR</p>
    <p>. DEFENSOR INTENSO Y FISICO</p>
    <p>. FUERTE Y CON BRAZOS MUY LARGOS</p>
    <p>. CORRECTO REBOTERO; SUMA TAPONES</p>
    <p>. JUGABA EN UN NIVEL NCAA MUY BAJO</p>
    <p>. YA FIRMO CON EQUIPO DE CANADA</p>
    <p>. VALOR: UNDRAFTED</p>
  `,

  "FLETCHER LOYER": `
    <h3>SCOUTING REPORT</h3>
    <p>. ALTURA PROMEDIO PARA DOS</p>
    <p>. BRAZOS CORTOS; LE FALTAN KILOS</p>
    <p>. SIN CAPACIDAD ATLETICA NBA</p>
    <p>. ESPECIALISTA TRIPLERO</p>
    <p>. GRAN MECANICA; TIRO VELOZ</p>
    <p>. BUENOS MOVIMIENTOS SIN BALON</p>
    <p>. RARA VEZ LLEGA HASTA EL ARO</p>
    <p>. POCA CREACION CON EL BALON</p>
    <p>. DEFENSOR 100% VULNERABLE</p>
    <p>. MAL REBOTERO, POCO STL O BLK</p>
    <p>. VALOR: UNDRAFTED</p>
  `,

  "ALLEN GRAVES": `
    <h3>SCOUTING REPORT</h3>
    <p>. FUERTE PERO BAJO PARA 4-5</p>
    <p>. NO ES UN JUGADOR ATLETICO</p>
    <p>. BUEN TRIPLERO, CON ALCANCE NBA</p>
    <p>. MECANICA BASTANTE LENTA</p>
    <p>. EXCELENTE REBOTERO OFENSIVO</p>
    <p>. SIN EXPLOSION/ALTURA PARA DEFINIR</p>
    <p>. MUY BUEN PASADOR; BUENAS MANOS</p>
    <p>. BUEN JUGADOR DE PICK 'N ROLL/POP</p>
    <p>. DEFENSOR PESADO, VULNERABLE</p>
    <p>. AGRESIVO: MUCHOS ROBOS Y FALTAS</p>
    <p>. VALOR: FINAL 1° RONDA/2° RONDA</p>
  `,

  "KOBE KNOX": `
    <h3>SCOUTING REPORT</h3>
    <p>. ALTURA IDEAL PARA 2; BRAZOS LARGOS</p>
    <p>. SOLIDA CAPACIDAD ATLETICA; VELOZ</p>
    <p>. 32% EN 3P EN LOS ULTIMOS 3 AÑOS</p>
    <p>. 41% EN 3P EN SU PRIMER AÑO</p>
    <p>. BUEN DEFINIDOR: 58% 2P EN 4 AÑOS</p>
    <p>. MUY POCA CREACION PROPIA</p>
    <p>. APORTA POCO COMO PASADOR</p>
    <p>. LARGO Y VELOZ PERO LE FALTAN KILOS</p>
    <p>. POCO REBOTE; PIERDE FISICAMENTE</p>
    <p>. HERRAMIENTAS NBA; TALENTO G LEAGUE</p>
    <p>. VALOR: UNDRAFTED</p>
  `,

  "ERNEST UDEH": `
    <h3>SCOUTING REPORT</h3>
    <p>. ALTO, FUERTE, BRAZOS MUY LARGOS</p>
    <p>. NO ES EL ATLETA MAS VELOZ O AGIL</p>
    <p>. ULTRA LIMITADO EN ATAQUE</p>
    <p>. 73% FG = SOLO TIROS SENCILLOS</p>
    <p>. NI UN TIRO FUERA DE LA PINTURA</p>
    <p>. SIN JUEGO CON LA BOLA</p>
    <p>. 50% EN TIROS LIBRES</p>
    <p>. ESPECIALISTA DEFENSIVO</p>
    <p>. MUY BUEN REBOTERO; INTERIOR FISICO</p>
    <p>. MENOS BLK DE LOS QUE SE ESPERARIA</p>
    <p>. VALOR: UNDRAFTED</p>
  `,

  "KOWACIE REEVES": `
    <h3>SCOUTING REPORT</h3>
    <p>. GRAN ALTURA PARA ESCOLTA</p>
    <p>. BUEN ATLETA; MUY VELOZ</p>
    <p>. VIENE DE GRAN AÑO TRIPLERO: 39%</p>
    <p>. EN LOS 4 AÑOS PREVIOS: 32% 3P</p>
    <p>. BUEN TIRO A MEDIA DISTANCIA</p>
    <p>. SIN CREACION CON LA BOLA</p>
    <p>. CARRERA: 133 TOV VS. 96 ASIS</p>
    <p>. DEFENSA INTENSA SOBRE LA BOLA</p>
    <p>. LIMITADO POR SU FALTA DE KILOS</p>
    <p>. POCO REBOTE; SUMA TAPONES</p>
    <p>. VALOR: UNDRAFTED</p>
  `,

  "AARON NKRUMAH": `
    <h3>SCOUTING REPORT</h3>
    <p>. MUY ALTO PARA 2; FALTA POTENCIA</p>
    <p>. SUMAMENTE AGIL; POCO EXPLOSIVO</p>
    <p>. TIRO IRREGULAR; 32% EN 3P EN 4 AÑOS</p>
    <p>. VIENE DE SU MEJOR AÑO DE TRES: 35%</p>
    <p>. BUEN PASADOR, SIN SER BASE NATURAL</p>
    <p>. LIVIANO PARA DEFINIR EN LA PINTURA</p>
    <p>. ESPECIALISTA DEFENSIVO; MUY INTENSO</p>
    <p>. PRESIONA Y GENERA PERDIDAS: 2.8 STL</p>
    <p>. BUEN REBOTERO; SUMA TAPONES</p>
    <p>. LIMITADO POR SU FALTA DE KILOS</p>
    <p>. VALOR: 2° RONDA</p>
  `,

  "NOAM YAACOV": `
    <h3>SCOUTING REPORT</h3>
    <p>. BAJO Y SIN GRAN FISICO; BRAZOS CORTOS</p>
    <p>. RAPIDO, ATLETICO, CON BUEN SALTO</p>
    <p>. BASE PURO Y TALENTOSO CON LA BOLA</p>
    <p>. 38% EN TRIPLES EN LA 2025-2026</p>
    <p>. 22% EN TRIPLES EN DOS AÑOS PREVIOS</p>
    <p>. MEJOR EN LA MEDIA DISTANCIA</p>
    <p>. BUEN MANEJO, CREATIVO, ATACA</p>
    <p>. MUY BUEN PASADOR; PICK AND ROLL</p>
    <p>. DESVENTAJA FISICA EN DEFENSA</p>
    <p>. AYUDA EN EL REBOTE DEFENSIVO </p>
    <p>. VALOR: 2° RONDA</p>
  `,

  "TOBE AWAKA": `
    <h3>SCOUTING REPORT</h3>
    <p>. SIN GRAN ALTURA; CORRECTO ATLETA</p>
    <p>. EL JUGADOR MAS FUERTE DEL DRAFT</p>
    <p>. ANOTA MAYORMENTE DE REBOTES OF. </p>
    <p>. UNA BESTIA EN LA CARGA AL REBOTE</p>
    <p>. SIN GRAN TALENTO CON EL BALON</p>
    <p>. 5 3P EN 25-26; 2 EN 3 AÑOS PREVIOS</p>
    <p>. VIVE EN LA LINEA; 65% EN LIBRES</p>
    <p>. TAMBIEN DOMINA REBOTE DEFENSIVO</p>
    <p>. INAMOVIBLE EN EL CUERPO A CUERPO</p>
    <p>. SIN GRAN AGILIDAD; POCOS TAPONES</p>
    <p>. VALOR: 2° RONDA/UNDRAFTED</p>
  `,

  "NICK BOYD": `
    <h3>SCOUTING REPORT</h3>
    <p>. BASE BAJO, LIVIANO; BRAZOS CORTOS</p>
    <p>. VELOZ PERO NO TAN EXPLOSIVO</p>
    <p>. ANOTADOR; CREATIVO, SLASHER</p>
    <p>. BUEN MANEJO; AGRESIVO PARA ATACAR</p>
    <p>. ANOTA SEGUIDO EN TRANSICION</p>
    <p>. BUEN USO DE LA FLOTADORA</p>
    <p>. TRIPLERO CORRECTO: 37% EN 5 AÑOS</p>
    <p>. MAS ANOTACION QUE PASE; POCAS TOV</p>
    <p>. COMPITE Y PRESIONA EN DEFENSA</p>
    <p>. TOTALMENTE LIMITADO POR FISICO</p>
    <p>. VALOR: UNDRAFTED</p>
  `,

  "NICK MARTINELLI": `
    <h3>SCOUTING REPORT</h3>
    <p>. CARACTERISTICAS DE 4/5, ALTURA DE 3</p>
    <p>. SIN CAPACIDAD ATLETICA NBA</p>
    <p>. JUEGO HETERODOXO, OLD-SCHOOL</p>
    <p>. ANOTADOR DE 1 VS. 1, BUEN MANEJO</p>
    <p>. ATACA Y DEFINE CON GANCHOS RAPIDOS</p>
    <p>. ENCUENTRA ANGULOS DE TIRO EXTRAÑOS</p>
    <p>. POCO PASE; EL ARO ENTRE CEJA Y CEJA</p>
    <p>. BUEN TOQUE ALREDEDOR DE LA PINTURA</p>
    <p>. DEBAJO DE LA MEDIA COMO TRIPLERO</p>
    <p>. DEFENSOR TOTALMENTE EXPLOTABLE</p>
    <p>. VALOR: UNDRAFTED</p>
  `,

  "TOBI LAWAL": `
    <h3>SCOUTING REPORT</h3>
    <p>. ATLETA FUERA DE SERIE; MUY VELOZ</p>
    <p>. COMBINE: SALTO 1.14m (2° HISTORICO)</p>
    <p>. MUY LIMITADO CON EL BALON</p>
    <p>. ANOTA DE DEFINICION Y TRANSICION</p>
    <p>. ALGO DE TIRO A PIE FIRME: 32% 3P</p>
    <p>. SIN GRAN TOQUE: -70% EN LIBRES</p>
    <p>. EXCELENTE REBOTERO DEFENSIVO</p>
    <p>. SU IMPACTO EN DEFENSA ES BAJO</p>
    <p>. LE FALTA POTENCIA; MUCHAS FALTAS</p>
    <p>. POCOS TAPONES; NO ES ALTO NI LARGO</p>
    <p>. VALOR: UNDRAFTED</p>
  `,

  "KYLAN BOSWELL": `
    <h3>SCOUTING REPORT</h3>
    <p>. BAJO; BRAZOS LARGOS, MUY FUERTE</p>
    <p>. NO ES EL ATLETA MAS EXPLOSIVO</p>
    <p>. 27% EN 3P EN ULTIMOS DOS AÑOS</p>
    <p>. 38% EN 3P EN PRIMEROS DOS AÑOS</p>
    <p>. FISICO PARA ATACAR EL ARO; BUEN 2P%</p>
    <p>. TIENE DESTELLOS DE MUY BUEN PASADOR</p>
    <p>. SIN UN DRIBLE DEMASIADO DINAMICO</p>
    <p>. DEFENSOR INTENSO, FISICO, FUERTE</p>
    <p>. POCOS ROBOS; 0 TAPONES EN 901 MIN.</p>
    <p>. AYUDA EN EL REBOTE DEFENSIVO</p>
    <p>. VALOR: UNDRAFTED</p>
  `,

  "IZAIYAH NELSON": `
    <h3>SCOUTING REPORT</h3>
    <p>. VELOZ, AGIL Y CON BRAZOS LARGOS</p>
    <p>. LE FALTA POTENCIA; SIN GRAN ALTURA</p>
    <p>. PELIGROSO EN TRANSICION</p>
    <p>. DEFINIDOR EXPLOSIVO EN LA PINTURA</p>
    <p>. PUEDE ATACAR POR VELOCIDAD</p>
    <p>. SIN BUENAS HABILIDADES TECNICAS</p>
    <p>. MAL TIRADOR DE LARGA DISTANCIA</p>
    <p>. DEFENSOR VERSATIL POR AGILIDAD</p>
    <p>. MUY BUEN REBOTERO EN AMBOS AROS</p>
    <p>. FALTAN KILOS PARA DEFENSA INTERIOR</p>
    <p>. VALOR: UNDRAFTED</p>
  `,

  "KEYSHAWN HALL": `
    <h3>SCOUTING REPORT</h3>
    <p>. BUENA ALTURA Y FISICO PARA 3</p>
    <p>. NO ES UN ATLETA MUY EXPLOSIVO</p>
    <p>. BUEN JUEGO CON EL BALON</p>
    <p>. AGRESIVO PARA ATACAR; SLASHER</p>
    <p>. VIVE EN LA LINEA DE LIBRES; +80 FT%</p>
    <p>. CORRECTO PASADOR; CREATIVO</p>
    <p>. VIENE DE SU MEJOR AÑO TRIPLERO</p>
    <p>. MUY MALA MECANICA DE TIRO</p>
    <p>. EXCELENTE REBOTERO; SUMA TAPONES</p>
    <p>. NO ES UN GRAN DEFENSOR 1 VS. 1</p>
    <p>. VALOR: UNDRAFTED</p>
  `,

  "UGONNA ONYENSO": `
    <h3>SCOUTING REPORT</h3>
    <p>. GRAN ALTURA Y BRAZOS XXL</p>
    <p>. APENAS PROMEDIO EN LO ATLETICO</p>
    <p>. JUGADOR OFENSIVO MUY LIMITADO</p>
    <p>. SOLO TERMINA JUGADAS, NO CREA</p>
    <p>. MUY SEGURO CERCA DEL ARO</p>
    <p>. 10 3P EN 2025-26; 0 PREVIAMENTE</p>
    <p>. PROTECCION DE ARO TOTALMENTE ELITE</p>
    <p>. PROMEDIO 6 BLK CADA 36 MINUTOS</p>
    <p>. POCAS FALTAS; TIMING PERFECTO</p>
    <p>. BUENO PERO NO GRAN REBOTERO</p>
    <p>. VALOR: 2° RONDA</p>
  `,

  "BRUCE THORNTON": `
    <h3>SCOUTING REPORT</h3>
    <p>. BASE SUPER FUERTE PERO BAJO</p>
    <p>. SIN CAPACIDAD ATLETICA NBA</p>
    <p>. BUEN TIRO DE MEDIA Y TRES PUNTOS</p>
    <p>. USA EL CUERPO PARA ABRIRSE PASO</p>
    <p>. SORPRENDENTE DEFINIDOR: 64% EN 2P</p>
    <p>. JUGADOR FISICO; DA EL PRIMER GOLPE</p>
    <p>. NO SOBRESALE COMO PASADOR</p>
    <p>. PROLIJO: 3 ASISTENCIAS POR PERDIDA</p>
    <p>. VA AL REBOTE Y COMPITE EN DEFENSA</p>
    <p>. VULNERABLE POR  ALTURA/VELOCIDAD</p>
    <p>. VALOR: UNDRAFTED</p>
  `,

  "DAILYN SWAIN": `
    <h3>SCOUTING REPORT</h3>
    <p>. GRAN ALTURA PARA ALERO</p>
    <p>. FLUIDO PERO NO SUPER ATLETICO</p>
    <p>. CREADOR CON EL BALON EN SUS MANOS</p>
    <p>. PISA LA PINTURA CON FRECUENCIA</p>
    <p>. MUY BUEN DEFINIDOR; GENERA FTA</p>
    <p>. BUEN PASADOR; POINT FORWARD</p>
    <p>. PROGRESO TRIPLERO PERO MAL TIRADOR</p>
    <p>. SIN BUENA MECANICA DE DISPARO</p>
    <p>. EXCELENTE JUGADOR DEFENSIVO</p>
    <p>. REBOTEA COMO PIVOT; MUCHAS STL</p>
    <p>. VALOR: FINAL 1° RONDA/2° RONDA</p>
  `,

  "RAFAEL CASTRO": `
    <h3>SCOUTING REPORT</h3>
    <p>. BUENA ALTURA Y VELOCIDAD</p>
    <p>. NO ES EL 5 MAS FUERTE O GRANDE</p>
    <p>. DOMINIO INTERIOR EN NIVEL NCAA BAJO</p>
    <p>. MUY EFICAZ EN LA PINTURA: 65% EN 2P</p>
    <p>. UN TRIPLE EN 123 JUEGOS; 63% EN FT</p>
    <p>. CORRE EL CAMPO, ANOTA EN TRANSICION</p>
    <p>. SOLIDO PASADOR, CON ALGO DE MANEJO</p>
    <p>. ESPECIALISTA DEFENSIVO; VERSATIL</p>
    <p>. ROBOS + TAPONES + REBOTES</p>
    <p>. BUENA DEFENSA PERIMETRAL; AGIL</p>
    <p>. VALOR: UNDRAFTED</p>
  `,

  "ALEX KARABAN": `
    <h3>SCOUTING REPORT</h3>
    <p>. CORRECTA ALTURA PARA 3/4</p>
    <p>. FUERTE PERO NO ATLETICO</p>
    <p>. ESPECIALISTA EN CATCH AND SHOOT</p>
    <p>. GRAN ALCANCE EN SU TIRO DE TRES</p>
    <p>. POCA CREACION CON EL BALON</p>
    <p>. PISA POCO LA PINTURA; MAL DEFINIDOR</p>
    <p>. JUGADOR INTELIGENTE; 100% DE EQUIPO</p>
    <p>. DEFENSOR AGUERRIDO, COMPETITIVO</p>
    <p>. LIMITADO POR CAPACIDAD ATLETICA</p>
    <p>. NO ES EL MEJOR REBOTERO EN DEFENSA</p>
    <p>. VALOR: 2° RONDA</p>
  `,

  "BABA MILLER": `
    <h3>SCOUTING REPORT</h3>
    <p>. GRAN ALTURA PARA SER 4</p>
    <p>. NO TAN EXPLOSIVO PERO MUY AGIL</p>
    <p>. DEBE FORTALECER SU CUERPO</p>
    <p>. MAL TIRADOR; 62% EN LIBRES</p>
    <p>. 3P: CARRERA = 29%, 2025-2026 = 19%</p>
    <p>. EXCELENTE MANEJO PARA SU ESTATURA</p>
    <p>. MUY BUEN PASADOR; DESPRENDIDO</p>
    <p>. CORRE MUY BIEN LA CANCHA; VELOZ</p>
    <p>. DEFENSOR VERSATIL; GRAN REBOTERO</p>
    <p>. AGIL PARA EL PERIMETRO; ENERGIA</p>
    <p>. VALOR: 2° RONDA</p>
  `,

  "ZUBY EJIOFOR": `
    <h3>SCOUTING REPORT</h3>
    <p>. MUY FUERTE PERO INTERIOR BAJO</p>
    <p>. BUEN ATLETA; AGIL + SALTO + FUERZA</p>
    <p>. BUEN MANEJO; ATACA CON POTENCIA</p>
    <p>. DEFINIDOR INSEGURO; FALTA ALTURA</p>
    <p>. SACA MUCHAS FALTAS; 70% EN LIBRES</p>
    <p>. LANZO UN 28% EN TRIPLES EN 4 AÑOS</p>
    <p>. BUEN PASADOR DESDE POSTE ALTO</p>
    <p>. DEFENSOR FISICO Y VERSATIL</p>
    <p>. RAPIDO EN EL PERIMETRO; STL + BLK</p>
    <p>. NO ES UN BUEN REBOTERO DEFENSIVO</p>
    <p>. VALOR: 2° RONDA</p>
  `,

  "BRADEN SMITH": `
    <h3>SCOUTING REPORT</h3>
    <p>. SIN ALTURA O POTENCIA NBA</p>
    <p>. VELOZ Y CON ALGO DE SALTO</p>
    <p>. BASE PURO; EXCELENTE PASADOR</p>
    <p>. ORGANIZADOR; INTELIGENTE</p>
    <p>. JUGADOR DE PICK AND ROLL</p>
    <p>. GRAN RELACION ASIS VS. TOV</p>
    <p>. BUEN TIRO DE MEDIA DISTANCIA</p>
    <p>. POR DEBAJO DE LA MEDIA EN TRIPLES</p>
    <p>. SIN ANOTACION INTERIOR</p>
    <p>. EXPLOTABLE EN DEFENSA POR FISICO</p>
    <p>. VALOR: UNDRAFTED</p>
  `,

  "ROBERT MCCRAY": `
    <h3>SCOUTING REPORT</h3>
    <p>. ALTURA PROMEDIO PARA BASE</p>
    <p>. GRAN ATLETA; VELOCIDAD Y SALTO</p>
    <p>. TRIPLERO IRREGULAR; POCA MEDIA</p>
    <p>. 35% EN 3P EN 2025-26 Y CARRERA</p>
    <p>. APENAS SUPERA EL 70% EN LIBRES</p>
    <p>. EXCELENTE MANEJO; CREADOR</p>
    <p>. ATACA, PISA LA PINTURA; 1 VS. 1</p>
    <p>. MUCHAS ASISTENCIAS Y PERDIDAS</p>
    <p>. SUMA REBOTES, ROBOS Y TAPONES</p>
    <p>. MEJORES NUMEROS QUE DEFENSA</p>
    <p>. VALOR: UNDRAFTED</p>
  `,

  "REYNAN DOS SANTOS": `
    <h3>SCOUTING REPORT</h3>
    <p>. SIN GRAN ALTURA PARA 2-3</p>
    <p>. RAPIDO PERO NO TAN EXPLOSIVO</p>
    <p>. MEJORANDO COMO TRIPLERO</p>
    <p>. VIENE DE SU MEJOR AÑO: 38% EN 3P</p>
    <p>. SOLO UN 31% EN LA 2024-2025</p>
    <p>. SIN EL DRIBLE MAS SEGURO</p>
    <p>. NO DESEQUILIBRA EN EL 1 VS. 1</p>
    <p>. NO SOBRESALE COMO PASADOR</p>
    <p>. DEFENSOR COMPETITIVO, FUERTE</p>
    <p>. SUMA ROBOS; POCO REBOTE O TAPAS</p>
    <p>. VALOR: UNDRAFTED</p>
  `,

  "ZACH CLEVELAND": `
    <h3>SCOUTING REPORT</h3>
    <p>. SIN GRAN ALTURA PARA 3-4</p>
    <p>. SOLIDO DESDE LO ATLETICO</p>
    <p>. SIN TIRO EXTERIOR NI MEDIA</p>
    <p>. 4 TRIPLES EN 126 PARTIDOS NCAA</p>
    <p>. RONDA EL 50% EN TIROS LIBRES</p>
    <p>. MAS PELIGROSO ATACANDO EL ARO</p>
    <p>. BUEN MANEJO; CREA CON LA BOLA</p>
    <p>. QUIZA EL MEJOR PASADOR DEL DRAFT</p>
    <p>. BUEN REBOTERO; SUMA STL Y BLK</p>
    <p>. DEFENSA: FALTA POTENCIA Y ALTURA</p>
    <p>. VALOR: UNDRAFTED</p>
  `,

  "JADEN HENLEY": `
    <h3>SCOUTING REPORT</h3>
    <p>. ALTURA PROMEDIO PARA 3</p>
    <p>. BRAZOS CORTOS; POCO ATLETICO</p>
    <p>. 27% 3P EN 2025-26 (CARRERA: 31%)</p>
    <p>. MUY AGRESIVO PARA PENETRAR</p>
    <p>. ANOTA EN TRANSICION; ATACA</p>
    <p>. VIVE EN LA LINEA DE LIBRES</p>
    <p>. IRREGULAR COMO DEFINIDOR</p>
    <p>. MAS PERDIDAS QUE ASISTENCIAS</p>
    <p>. GRAN REBOTERO; MUCHOS ROBOS</p>
    <p>. BUEN DEFENSOR EN GENERAL</p>
    <p>. VALOR: UNDRAFTED</p>
  `,

  "EBUKA OKORIE": `
    <h3>SCOUTING REPORT</h3>
    <p>. BAJO; CON BRAZOS MUY LARGOS</p>
    <p>. BUEN ATLETA; VELOZ, ESCURRIDIZO</p>
    <p>. TALENTO PURO CON EL BALON</p>
    <p>. SLASHER; MANEJO + VELOCIDAD</p>
    <p>. VIVE EN LA PINTURA Y EN LA LINEA</p>
    <p>. BUEN DEFINIDOR; FLEXIBILIDAD TOP</p>
    <p>. SOLIDO TIRADOR EN MOVIMIENTO</p>
    <p>. APENAS DESTELLOS COMO PASADOR</p>
    <p>. INTENSO EN DEFENSA; SUMA ROBOS</p>
    <p>. ATACABLE POR FALTA DE FISICO</p>
    <p>. VALOR: PICK DE PRIMERA RONDA</p>
  `,

  "FELIX OKPARA": `
    <h3>SCOUTING REPORT</h3>
    <p>. BUENA ALTURA; LE FALTAN KILOS</p>
    <p>. EXCELENTE CAPACIDAD ATLETICA</p>
    <p>. SUPER LIMITADO EN ATAQUE</p>
    <p>. DEFINIDOR DE ALLEY-OOPS</p>
    <p>. SIN TALENTO PARA CREAR CON LA BOLA</p>
    <p>. ANOTO 4 TRIPLES EN LA 2025-26</p>
    <p>. DESTACADO JUGADOR DEFENSIVO</p>
    <p>. VELOZ; PUEDE DEFENDER AFUERA</p>
    <p>. DA TAPONES DESCOMUNALES</p>
    <p>. POCO REBOTE; LIVIANO PARA EL POSTE</p>
    <p>. VALOR: 2° RONDA</p>
  `,

  "HANNES STEINBACH": `
    <h3>SCOUTING REPORT</h3>
    <p>. ALTURA Y POTENCIA FISICA IDEAL</p>
    <p>. BUENA AGILIDAD; SIN EXPLOSION</p>
    <p>. SIN GRAN CREACION CON EL BALON</p>
    <p>. SEGURO COMO DEFINIDOR</p>
    <p>. CORRE MUY BIEN LA CANCHA</p>
    <p>. EL MEJOR REBOTERO DEL DRAFT 2026</p>
    <p>. BUEN PASADOR, SIN SER BRILLANTE</p>
    <p>. PUEDE ANOTAR EL 3P FRONTAL ABIERTO</p>
    <p>. SIN PROTECCION DE ARO EN DEFENSA </p>
    <p>. SUMA ROBOS; BUENA MOVILIDAD</p>
    <p>. VALOR: PICK DE PRIMERA RONDA</p>
  `,

  "CAMERON CARR": `
    <h3>SCOUTING REPORT</h3>
    <p>. GRAN ATLETA Y BUENA ALTURA PARA 2</p>
    <p>. LE FALTA GANAR POTENCIA FISICA</p>
    <p>. ANOTADOR Y EXCELENTE TIRADOR</p>
    <p>. GRAN FLUIDEZ Y MECANICA DE TIRO</p>
    <p>. ALCANCE NBA; TIRA EN MOVIMIENTO</p>
    <p>. EXPLOSIVO PARA ATACAR Y DEFINIR</p>
    <p>. POCO PASE; EL ARO ENTRE CEJA Y CEJA</p>
    <p>. MALA SELECCION DE TIRO; EGOISTA</p>
    <p>. MAL DEFENSOR POR FALTA DE KG</p>
    <p>. SU EXPLOSION LO HACE SUMAR REB/BLK</p>
    <p>. VALOR: PICK DE LOTERIA</p>
  `,

  "HENRI VEESAAR": `
    <h3>SCOUTING REPORT</h3>
    <p>. GRAN ALTURA; NO TAN POTENTE</p>
    <p>. MAL ATLETA EN TERMINOS NBA</p>
    <p>. ESPECIALISTA TRIPLERO; PICK AND POP</p>
    <p>. ALREDEDOR DEL 60% EN TIROS LIBRES</p>
    <p>. BUEN TOQUE ALREDEDOR DEL ARO</p>
    <p>. CORRECTO PASADOR; POCAS PERDIDAS</p>
    <p>. EVIDENTES PROBLEMAS DEFENSIVOS</p>
    <p>. NO PROTEGE EL ARO; POCAS TAPAS</p>
    <p>. SIN GRAN VELOCIDAD PERIMETRAL</p>
    <p>. NO ES EL REBOTERO MAS SEGURO</p>
    <p>. VALOR: 2° RONDA</p>
  `,

  "DARIUS ACUFF": `
    <h3>SCOUTING REPORT</h3>
    <p>. BASE MUY FUERTE PERO BAJO</p>
    <p>. PROMEDIO DESDE LO ATLETICO</p>
    <p>. TRIPLERO LETAL: 44% EN 6 3PA</p>
    <p>. MUY BUEN TIRO EN MOVIMIENTO</p>
    <p>. ATACA; CORRECTO DEFINIDOR</p>
    <p>. JUEGO AGRESIVO; ANOTADOR</p>
    <p>. MENTALIDAD DE ESTRELLA</p>
    <p>. BUEN PASADOR; 3 ASIS X CADA TOV</p>
    <p>. PESIMO JUGADOR DEFENSIVO</p>
    <p>. SIN ALTURA NI ENFOQUE DEFENSIVO</p>
    <p>. VALOR: PICK DE PRIMERA RONDA</p>
  `,

  "TAMIN LIPSEY": `
    <h3>SCOUTING REPORT</h3>
    <p>. BASE FUERTE PERO BAJO</p>
    <p>. NO DESTACA DESDE LO ATLETICO</p>
    <p>. MAL TIRADOR DE TRIPLES Y LIBRES</p>
    <p>. MAS EFECTIVO ATACANDO EL ARO</p>
    <p>. USA Y DEPENDE DE LA FLOTADORA</p>
    <p>. BUEN PASADOR; INTELIGENTE, LIDER</p>
    <p>. GRAN RELACION DE ASIS VS. TOV</p>
    <p>. PESTE DEFENSIVA AUN SIENDO BAJO</p>
    <p>. SUPER DEDICADO Y MUY FISICO</p>
    <p>. ESPECIALISTA EN ROBOS; REBOTEA</p>
    <p>. VALOR: UNDRAFTED</p>
  `,

  "LABARON PHILON": `
    <h3>SCOUTING REPORT</h3>
    <p>. BASE MUY VELOZ, ESCURRIDIZO</p>
    <p>. LIVIANO Y SIN GRAN ESTATURA</p>
    <p>. ESPECIALISTA EN ATACAR LA PINTURA</p>
    <p>. COMBINA VELOCIDAD Y DRIBLE</p>
    <p>. MUY BUEN DEFINIDOR CERCA DEL ARO</p>
    <p>. VIENE DE UN GRAN AÑO DE 3P (40%)</p>
    <p>. SOLO 31% 3P EN TEMPORADA PREVIA </p>
    <p>. MAS ANOTADOR QUE ORGANIZADOR</p>
    <p>. PAGA SU FALTA DE KG EN DEFENSA</p>
    <p>. CONTRIBUYE CON PRESION/ROBOS</p>
    <p>. VALOR: PICK DE PRIMERA RONDA</p>
  `,

  "JA'KOBI GILLESPIE": `
    <h3>SCOUTING REPORT</h3>
    <p>. BASE BAJO PERO MUY ATLETICO</p>
    <p>. TIENE VELOCIDAD Y SALTO NBA</p>
    <p>. ANOTADOR, SOBRE TODO EXTERIOR</p>
    <p>. NO ELITE PERO ES UN BUEN TRIPLERO</p>
    <p>. MUCHISIMO ARCO EN SU DISPARO</p>
    <p>. LE CUESTA ANOTAR EN LA PINTURA</p>
    <p>. NO DESTACA COMO ORGANIZADOR </p>
    <p>. DEFENSOR COMPETITIVO E INTENSO</p>
    <p>. GRAN CANTIDAD DE ROBOS</p>
    <p>. OBVIAMENTE LIMITADO POR ESTATURA</p>
    <p>. VALOR: UNDRAFTED</p>
  `,

  "MALIK RENEAU": `
    <h3>SCOUTING REPORT</h3>
    <p>. ALTURA DE 4, VELOCIDAD DE 5</p>
    <p>. SIN BUENA EXPLOSION ATLETICA</p>
    <p>. CREA DE FRENTE Y DE ESPALDAS</p>
    <p>. BUEN MANEJO Y MOVIMIENTOS DE PIES</p>
    <p>. DEFINIDOR DE TOQUE, NO DE POTENCIA</p>
    <p>. FISICO; VIVE EN LA LINEA, ANOTA FTs</p>
    <p>. TIRO MEJORADO: 35% EN LA 2025-26</p>
    <p>. BUEN PASADOR, BUENA LECTURA</p>
    <p>. DEFENSOR DE MUY BAJO IMPACTO</p>
    <p>. MAL REBOTERO Y NO PROTEGE EL ARO</p>
    <p>. VALOR: UNDRAFTED</p>
  `,

  "MALIQ BROWN": `
    <h3>SCOUTING REPORT</h3>
    <p>. 4-5 SIN GRAN ALTURA O PESO</p>
    <p>. MUY VELOZ; NO TAN EXPLOSIVO</p>
    <p>. MUY FISICO PARA SU TAMAÑO</p>
    <p>. SIN APORTE COMO ANOTADOR</p>
    <p>. NO CREA CON LA BOLA; MAL TIRADOR</p>
    <p>. BUEN PASADOR DESDE POSTE ALTO</p>
    <p>. DEFENSOR ULTRA COMPETITIVO </p>
    <p>. BATALLA ANTE RIVALES MAS GRANDES</p>
    <p>. MANOS RAPIDISIMAS PARA ROBOS</p>
    <p>. POCO REBOTE Y TAPONES</p>
    <p>. VALOR: UNDRAFTED</p>
  `,

  "TREY KAUFMAN RENN": `
    <h3>SCOUTING REPORT</h3>
    <p>. FUERTE PERO BAJO; BRAZOS CORTOS</p>
    <p>. SIN CAPACIDAD ATLETICA NBA</p>
    <p>. INTERIOR OLD-SCHOOL; TALENTOSO</p>
    <p>. BUEN JUEGO DE POSTE; GRAN TOQUE</p>
    <p>. DOMINA SI TIENE VENTAJA FISICA</p>
    <p>. PROBLEMAS ANTE PIVOTS GRANDES</p>
    <p>. EXCELENTE PASADOR; BUEN MANEJO </p>
    <p>. LE FALTA TIRO EXTERIOR; 63% EN FT</p>
    <p>. BUEN REBOTERO EN AMBOS TABLEROS</p>
    <p>. MAL DEFENSOR; NO DA TAPONES</p>
    <p>. VALOR: UNDRAFTED</p>
  `,

  "TYLER BILODEAU": `
    <h3>SCOUTING REPORT</h3>
    <p>. ALGO BAJO PARA SU POSICION</p>
    <p>. SIN CAPACIDAD ATLETICA NBA</p>
    <p>. CONSOLIDADO COMO GRAN TIRADOR</p>
    <p>. 46% 3P EN 4.5 INTENTOS EN LA 25-26</p>
    <p>. ARRIBA DEL 85% EN TIROS LIBRES</p>
    <p>. EN LA NCAA ATACABA DESDE EL DRIBLE</p>
    <p>. NO SERA SU ROL NBA -SIN VELOCIDAD- </p>
    <p>. NO SOBRESALE COMO PASADOR</p>
    <p>. DEFENSOR TOTALMENTE VULNERABLE</p>
    <p>. SOLIDO REBOTERO; SIN TAPONES</p>
    <p>. VALOR: UNDRAFTED</p>
  `,

  "CALEB WILSON": `
    <h3>SCOUTING REPORT</h3>
    <p>. ALTURA Y CAPACIDAD ATLETICA IDEAL</p>>
    <p>. UNA MAQUINA DE VOLCAR LA BOLA</p>
    <p>. AMENAZA CONSTANTE EN TRANSICION</p>
    <p>. ABUSA DEL FADEAWAY EN POSTE BAJO</p>
    <p>. SIN MANEJO PARA CREAR DE FRENTE</p>
    <p>. MAL TIRADOR, SIN BUENA MECANICA</p>
    <p>. TALENTO PASADOR PERO FRENA LA BOLA</p>
    <p>. POTENCIAL DEFENSIVO DE ELITE</p>
    <p>. DOMINA REBOTE; SUMA STL Y BLK</p>
    <p>. BUEN DEFENSOR DE 1 VS. 1</p>
    <p>. VALOR: PICK TOP 5</p>
  `,

  "JOSHUA JEFFERSON": `
    <h3>SCOUTING REPORT</h3>
    <p>. SIN GRAN ALTURA PERO FUERTE</p>
    <p>. LE FALTA VELOCIDAD Y EXPLOSION</p>
    <p>. JUGADOR TALENTOSO CON EL BALON</p>
    <p>. CREA DESDE POSTE BAJO Y ALTO</p>
    <p>. MUY BAJOS % COMO DEFINIDOR</p>
    <p>. CAPAZ DE ANOTAR TRIPLES ABIERTOS</p>
    <p>. SU MAYOR VIRTUD: PASE Y LECTURA</p>
    <p>. DEFENSOR INTELIGENTE Y DEDICADO</p>
    <p>. MUY BUENA SUMA DE REBOTES Y ROBOS</p>
    <p>. DEFENSA LIMITADA POR CAP. ATLETICA</p>
    <p>. VALOR: FINAL 1° RONDA/2° RONDA</p>
  `,

  "TARRIS REED": `
    <h3>SCOUTING REPORT</h3>
    <p>. BUENA ALTURA, MUY FUERTE</p>
    <p>. MAS MOVIL QUE VELOZ O EXPLOSIVO</p>
    <p>. PIVOT OLD-SCHOOL: POTENCIA Y POSTE</p>
    <p>. GRANDES MOVIMIENTOS DE ESPALDAS</p>
    <p>. ANOTA DE ZURDA Y DERECHA</p>
    <p>. BUEN PASADOR; POCAS PERDIDAS</p>
    <p>. SIN TIRO DE MEDIA NI TRES PUNTOS</p>
    <p>. SOLO UN 60% EN TIROS LIBRES</p>
    <p>. DOMINA EL REBOTE EN AMBOS AROS</p>
    <p>. DEFENSA LIMITADA POR CAP. ATLETICA</p>
    <p>. VALOR: 2° RONDA</p>
  `,

  "CAM BOOZER": `
    <h3>SCOUTING REPORT</h3>
    <p>. ALTURA DE 4; POTENCIA DE 5</p>
    <p>. MUY FUERTE; NO SUPER ALETICO</p>
    <p>. UN TORO PARA ATACAR EL ARO</p>
    <p>. LETAL VS. MISMATCHES EN LA PINTURA</p>
    <p>. NO TAN DOMINANTE VS. 5s GRANDES</p>
    <p>. SOLIDO 3P A PIE FIRME; METE LIBRES</p>
    <p>. EXCELENTE PASADOR; 2 ASIS POR 1 TOV</p>
    <p>. ENDEBLE DEFENSA INTERIOR; SIN BLK</p>
    <p>. SIN GRAN AGILIDAD PARA EL PERIMETRO</p>
    <p>. MUY BUEN REBOTERO EN AMBOS AROS</p>
    <p>. VALOR: PICK TOP 3</p>
  `,

  "TREVON BRAZILE": `
    <h3>SCOUTING REPORT</h3>
    <p>. ALTURA Y EXPLOSION IDEAL PARA EL 4</p>
    <p>. LE FALTA POTENCIA Y JUEGO FISICO</p>
    <p>. SOLIDO TRIPLERO A PIE FIRME</p>
    <p>. DEFINIDOR EXPLOSIVO, VOLCADOR</p>
    <p>. ANOTA MUY SEGUIDO EN TRANSICION</p>
    <p>. SIN JUEGO DE POSTE; NO CREA TIROS</p>
    <p>. GRANDES HERRAMIENTAS DEFENSIVAS</p>
    <p>. SUMA ROBOS, TAPONES Y REBOTES</p>
    <p>. SIN POTENCIA PARA DEFENDER 5s NBA</p>
    <p>. MUY IRREGULAR; DESAPARECE, VOLATIL</p>
    <p>. VALOR: 2° RONDA</p>
  `,

  "BENNETT STIRTZ": `
    <h3>SCOUTING REPORT</h3>
    <p>. BASE PURO, CON PASE Y TIRO</p>
    <p>. SIN BUENA ALTURA O POTENCIA</p>
    <p>. BUEN TIRADOR DE MEDIA Y 3 PUNTOS</p>
    <p>. 3P% IRREGULAR = DIFICULTAD DE TIROS</p>
    <p>. MUY BUEN PASADOR; CREATIVO, PRECISO</p>
    <p>. CREADOR DESDE EL PICK AND ROLL</p>
    <p>. NO GENERA SEPARACION EN 1 VS. 1</p>
    <p>. SU ESFUERZO DEFENSIVO NO ALCANZA</p>
    <p>. CLARA DESVENTAJA FISICA VS. NBA</p>
    <p>. MAL REBOTERO, INCLUSO EN LA NCAA</p>
    <p>. VALOR: 2° RONDA</p>
  `,

  "TYLER NICKEL": `
    <h3>SCOUTING REPORT</h3>
    <p>. ALERO DE BUENA ESTATURA Y FISICO</p>
    <p>. SIN CAPACIDAD ATLETICA NBA</p>
    <p>. 100% UNIDIMENSIONAL: SOLO TRIPLE</p>
    <p>. EL MEJOR TIRADOR PURO DEL DRAFT</p>
    <p>. MECANICA IDEAL, VELOZ; ALCANCE NBA</p>
    <p>. UN SOLO ROL, PERO ES ELITE EN EL</p>
    <p>. RARA VEZ PISA LA PINTURA; NO CREA</p>
    <p>. NO APORTA COMO PASADOR</p>
    <p>. SIN REBOTE; MUY MAL DEFENSOR</p>
    <p>. BLANCO FACIL PARA CUALQUIER NBA</p>
    <p>. VALOR: 2° RONDA</p>
  `,

  "YAXEL LENDEBORG": `
    <h3>SCOUTING REPORT</h3>
    <p>. GRAN ALTURA PARA 3/4; BUEN ATLETA</p>
    <p>. CORRECTO TRIPLERO A PIE FIRME</p>
    <p>. ANOTA EN TRANSICION; BUEN DEFINIDOR</p>
    <p>. SIN EL MEJOR DRIBLE PARA CREAR</p>
    <p>. FENOMENAL PASADOR PARA SU ALTURA</p>
    <p>. +3 ASISTENCIAS POR CADA PERDIDA</p>
    <p>. EXCELENTE JUGADOR DEFENSIVO</p>
    <p>. DEFIENDE 3 O 4 POSICIONES</p>
    <p>. MUY BUEN REBOTERO; SUMA STL+BLK</p>
    <p>. LA EDAD (24) LE QUITA POTENCIAL</p>
    <p>. VALOR: PICK DE LOTERIA</p>
  `,

  "MIKEL BROWN": `
    <h3>SCOUTING REPORT</h3>
    <p>. 1-2 SUPER VELOZ Y EXPLOSIVO</p>
    <p>. ANOTADOR NATURAL CON Y SIN BALON</p>
    <p>. GRAN TRIPLERO, CON ALCANCE NBA</p>
    <p>. 3P% BAJO = MALA SELECCION DE TIRO</p>
    <p>. BUENA MECANICA; TIRA EN MOVIMIENTO</p>
    <p>. IGUAL DE PELIGROSO ATACANDO EL ARO</p>
    <p>. VELOZ Y CON MANEJO; BUEN DEFINIDOR</p>
    <p>. VERTICAL, AGRESIVO; MUCHOS FTA</p>
    <p>. PASADOR "FLASHY" PERO ERRATICO</p>
    <p>. MAL DEFENSOR; LE FALTA POTENCIA</p>
    <p>. VALOR: PICK DE LOTERIA</p>
  `,

  "BRAYDEN BURRIES": `
    <h3>SCOUTING REPORT</h3>
    <p>. ALGO BAJO PARA LA POSICICION DE 1-2</p>
    <p>. FUERTE PERO NO SUPER EXPLOSIVO</p>
    <p>. EXCELENTE TRIPLERO; BUENA MECANICA</p>
    <p>. FLUIDO PARA TIRAR EN MOVIMIENTO</p>
    <p>. NO BRILLA EN EL JUEGO CON BALON</p>
    <p>. PROMEDIO COMO PASADOR Y SLASHER</p>
    <p>. MUY PELIGROSO EN TRANSICION</p>
    <p>. JUEGO MADURO, INTELIGENTE, TEMPLADO</p>
    <p>. DEFENSOR COMPLETO Y CON ENERGIA</p>
    <p>. VA AL REBOTE; VELOZ PARA ROTACIONES</p>
    <p>. VALOR: PICK TOP 10</p>
  `,

  "MOREZ JOHNSON": `
    <h3>SCOUTING REPORT</h3>
    <p>. ALTURA Y FISICO IDEAL PARA EL 4</p>
    <p>. BUEN ATLETA Y SUMAMENTE FUERTE</p>
    <p>. ANOTA EN LA PINTURA POR POTENCIA</p>
    <p>. PERO LE FALTA TOQUE Y TECNICA</p>
    <p>. GRAN REBOTERO OFENSIVO</p>
    <p>. BUENOS % EN LIBRES Y 3P EN ESQUINA</p>
    <p>. SIN APORTE COMO PASADOR/CREADOR</p>
    <p>. ESPECIALISTA DEFENSIVO; VERSATIL</p>
    <p>. DEFIENDE PERIMETRO + REBOTE + TAPAS</p>
    <p>. ES FISICO Y JUEGA CON MUCHA ENERGIA</p>
    <p>. VALOR: PICK DE PRIMERA RONDA</p>
  `,

  "KINGSTON FLEMINGS": `
    <h3>SCOUTING REPORT</h3>
    <p>. BAJO PERO SUMAMENTE VELOZ</p>
    <p>. UN RAYO PARA ATACAR EL ARO</p>
    <p>. SOLIDO DEFINIDOR PARA SU ALTURA</p>
    <p>. ESPECIALISTA EN TIRO DE MEDIA</p>
    <p>. TIRA POCO Y DEJA DUDAS DESDE 3P</p>
    <p>. MALA MECANICA DE LANZAMIENTO</p>
    <p>. MUY BUEN PASADOR; BASE NATURAL</p>
    <p>. 3 ASISTENCIAS POR CADA PERDIDA</p>
    <p>. DEFENSOR INTENSO; SUMA STL. Y REB.</p>
    <p>. LIMITADO POR SU FALTA DE ALTURA</p>
    <p>. VALOR: PICK DE PRIMERA RONDA</p>
  `,

  "CHRIS CENAC": `
    <h3>SCOUTING REPORT</h3>
    <p>. GRAN TAMAÑO PARA JUGAR DE 4-5</p>
    <p>. BUENA MOVILIDAD PARA SU ESTATURA</p>
    <p>. MUY BUEN TIRO DE MEDIA DISTANCIA</p>
    <p>. POTENCIAL TRIPLERO; HOY IRREGULAR</p>
    <p>. NO ES AMENAZA EN LA PINTURA</p>
    <p>. SIN JUEGO CON EL BALON O CREACION</p>
    <p>. VELOZ PARA DEFENDER EL PERIMETRO</p>
    <p>. GRAN REBOTERO EN AMBOS TABLEROS</p>
    <p>. NO ES EL JUGADOR MAS FISICO</p>
    <p>. BAJISIMA SUMA DE TAPONES</p>
    <p>. VALOR: PICK DE LOTERIA</p>
  `,

  "JAYDEN QUAINTANCE": `
    <h3>SCOUTING REPORT</h3>
    <p>. BUENA ALTURA; FUERTE, BRAZOS LARGOS</p>
    <p>. EXCELENTE CAPACIDAD ATLETICA</p>
    <p>. LESION DE RODILLA: 67 MIN. EN 25-26</p>
    <p>. JUGADOR DE PINTURA; DEFINIDOR</p>
    <p>. ANOTO 6 TRIPLES EN LA 2024-25</p>
    <p>. POR DEBAJO DEL 50% EN LIBRES </p>
    <p>. MUY BUEN REBOTERO OFENSIVO</p>
    <p>. GRAN POTENCIAL DEFENSIVO</p>
    <p>. INTENSO, FISICO; ALGO CAOTICO</p>
    <p>. GRAN SUMA DE TAPONES Y ROBOS</p>
    <p>. VALOR: PICK DE LOTERIA</p>
  `,

  "KOA PEAT": `
    <h3>SCOUTING REPORT</h3>
    <p>. TAMAÑO IDEAL PARA EL ROL DE 3-4</p>
    <p>. SOLIDO ATLETA; FUERTE, POTENTE</p>
    <p>. AGRESIVO, FISICO PARA ATACAR EL ARO</p>
    <p>. IRREGULAR COMO DEFINIDOR</p>
    <p>. FUERZA DISPAROS INCOMODOS</p>
    <p>. MUCHO TIRO DE MEDIA, CON BAJOS %</p>
    <p>. HOY, SIN DISTANCIA NBA EN EL TIRO</p>
    <p>. EXCELENTE PASADOR Y BUEN DRIBLE</p>
    <p>. BUEN DEFENSOR PERIMETRAL VS. 3/4</p>
    <p>. BUEN REBOTERO;  BAJO EN TAPONES</p>
    <p>. VALOR: PICK DE PRIMERA RONDA</p>
  `,

  "NATE AMENT": `
    <h3>SCOUTING REPORT</h3>
    <p>. ALTURA + VELOCIDAD + MANEJO</p>
    <p>. CREATIVO CON EL BALON, BUEN DRIBLE</p>
    <p>. MUY BUEN PASADOR PARA SU ALTURA</p>
    <p>. TIRO IRREGULAR DE MEDIA Y LARGA</p>
    <p>. SIN LA MECANICA MAS FLUIDA O PURA</p>
    <p>. LE FALTAN KILOS; MAL DEFINIDOR</p>
    <p>. GRAN GENERADOR DE TIROS LIBRES</p>
    <p>. PELIGROSO EN TRANSICION</p>
    <p>. DEFENSOR VERSATIL; BUEN REBOTERO</p>
    <p>. LIMITADO POR FALTA DE POTENCIA</p>
    <p>. VALOR: PICK DE PRIMERA RONDA</p>
  `,

  "KARIM LOPEZ": `
    <h3>SCOUTING REPORT</h3>
    <p>. ALTO Y CON BUEN FISICO PARA LA EDAD</p>
    <p>. NO ES EL ATLETA MAS EXPLOSIVO</p>
    <p>. TALENTO CON LA BOLA; CREA, ATACA</p>
    <p>. FUERTE PARA PENETRAR; DEFINE</p>
    <p>. TIRADOR IRREGULAR: 32% 3P</p>
    <p>. SIN GRAN MECANICA; TIRO A PIE FIRME</p>
    <p>. POR DEBAJO DEL 75% EN LIBRES</p>
    <p>. SOLIDO MANEJO Y PASE</p>
    <p>. EXCELENTE REBOTERO; SUMA STL+BLK</p>
    <p>. DEFENSA 1 VS 1 VULNERABLE</p>
    <p>. VALOR: PICK DE PRIMERA RONDA</p>
  `,

  "CHRISTIAN ANDERSON": `
    <h3>SCOUTING REPORT</h3>
    <p>. BASE BAJO Y SIN GRAN EXPLOSION</p>
    <p>. EXCELENTE TIRADOR DE TRES PUNTOS</p>
    <p>. MECANICA DE TIRO IDEAL</p>
    <p>. TIRO CERTERO EN MOVIMIENTO</p>
    <p>. MUY LIMITADO EN LA PINTURA</p>
    <p>. BUEN PASE Y JUEGO DE PICK AND ROLL</p>
    <p>. SIN HERRAMIENTAS DEFENSIVAS...</p>
    <p>. PERO COMPITE Y PRESIONA AL RIVAL</p>
    <p>. BASE DE CARACTER CON UN ROL CLARO</p>
    <p>. LIDERO EL BIG 12 EN MINUTOS JUGADOS</p>
    <p>. VALOR: PICK DE PRIMERA RONDA</p>
  `,

  "MELEEK THOMAS": `
    <h3>SCOUTING REPORT</h3>
    <p>. TAMAÑO DE BASE, JUEGO DE ESCOLTA</p>
    <p>. NO ES MUY EXPLOSIVO O POTENTE</p>
    <p>. ANOTADOR NATURAL; TIRADOR</p>
    <p>. 42% EN BUENA CANTIDAD DE 3P</p>
    <p>. MECANICA VELOZ; CONFIANZA PLENA</p>
    <p>. DISPARA Y ANOTA EN MOVIMIENTO</p>
    <p>. PROBLEMAS PARA DEFINIR; 44% EN 2P</p>
    <p>. NO MOSTRO CONDICIONES DE BASE</p>
    <p>. APORTA ROBOS Y ENERGIA EN DEFENSA</p>
    <p>. PERO ESTA LIMITADO POR SU FISICO</p>
    <p>. VALOR: PICK DE PRIMERA RONDA</p>
  `,

  "DARRYN PETERSON": `
    <h3>SCOUTING REPORT</h3>
    <p>. BUENA ALTURA Y CAPACIDAD ATLETICA</p>
    <p>. LETAL DE MEDIA Y LARGA DISTANCIA</p>
    <p>. ANOTADOR PURO; SHOTMAKER</p>
    <p>. BUEN DEFINIDOR CON TOQUE</p>
    <p>. NO PISA TANTO LA PINTURA</p>
    <p>. SIN TANTA CREACION CON LA BOLA</p>
    <p>. POCO PASE; RECIBE PARA TIRAR </p>
    <p>. DEFENSOR CORRECTO, NO DECISIVO</p>
    <p>. PROBLEMAS CON LAS LESIONES</p>
    <p>. DEBE GANAR POTENCIA Y KILOS</p>
    <p>. VALOR: PICK TOP 3</p>
  `,

  "QUADIR COPELAND": `
    <h3>SCOUTING REPORT</h3>
    <p>. ALTURA Y VELOCIDAD PARA LA POSICION</p>
    <p>. ESPECIALISTA EN ATACAR EL ARO</p>
    <p>. RECURSOS + PACIENCIA EN LA PINTURA</p>
    <p>. AUNQUE SIN GRAN TOQUE/FLOTADORA</p>
    <p>. CREATIVO Y MUY BUEN PASADOR</p>
    <p>. VIENE DE SU MEJOR AÑO TRIPLERO...</p>
    <p>. PERO SOLO UN 28.5% EN 3P EN 4 AÑOS</p>
    <p>. SUMA UNA BUENA CANTIDAD DE ROBOS</p>
    <p>. DEFENSOR LIVIANO, CON POCO REBOTE</p>
    <p>. ES MUY ALTO PERO LE FALTAN KILOS</p>
    <p>. VALOR: 2° RONDA/UNDRAFTED</p>
  `,

  "JADEN BRADLEY": `
    <h3>SCOUTING REPORT</h3>
    <p>. BASE DE ALTURA Y VELOCIDAD PROMEDIO</p>
    <p>. ATACA PERO NO ES EL MEJOR DEFINIDOR</p>
    <p>. MUY BUEN TIRO EN LA MEDIA DISTANCIA</p>
    <p>. 37% 3P PERO EN MUY POCOS INTENTOS</p>
    <p>. NO PARECE TENER ALCANCE NBA EN TIRO</p>
    <p>. NO BRILLA COMO PASADOR/ORGANIZADOR</p>
    <p>. CONSOLIDADO COMO BUEN DEFENSOR</p>
    <p>. MANOS RAPIDAS PARA LOS ROBOS</p>
    <p>. BUEN DEFENSOR DE 1 VS. 1; INTENSO</p>
    <p>. JUGADOR FISICO Y COMPETITIVO</p>
    <p>. VALOR: 2° RONDA/UNDRAFTED</p>
  `,

  "KEATON WAGLER": `
    <h3>SCOUTING REPORT</h3>
    <p>. ALTO Y HABIL CON EL BALON</p>
    <p>. LE FALTA EXPLOSION Y POTENCIA</p>
    <p>. MUY BUEN TIRADOR DE TRES PUNTOS</p>
    <p>. SIN JUEGO DE MEDIA DISTANCIA</p>
    <p>. CREATIVO Y PRECISO COMO DEFINIDOR</p>
    <p>. JUEGA A SU RITMO; POCAS PERDIDAS</p>
    <p>. PELIGROSO DESDE EL PICK AND ROLL</p>
    <p>. PASADOR CORRECTO, CON BUENA VISION</p>
    <p>. NO ANOTA EN TRANSICION</p>
    <p>. SIN GRAN POTENCIAL DEFENSIVO</p>
    <p>. VALOR: PICK TOP 10</p>
  `,

  "DARRION WILLIAMS": `
    <h3>SCOUTING REPORT</h3>
    <p>. TANQUE DE ENORME POTENCIA</p>
    <p>. CONSOLIDADO COMO TRIPLERO</p>
    <p>. SIN LA MECANICA DE TIRO MAS FLUIDA</p>
    <p>. MUY BUEN PASADOR Y BUEN DRIBLE</p>
    <p>. SIN EXPLOSION ATLETICA NI VELOCIDAD</p>
    <p>. JUEGA EN POSTE BAJO PERO INEFICAZ</p>
    <p>. MAL DEFINIDOR: 42.3% EN DOBLES</p>
    <p>. JUGADOR FISICO Y CON BUENAS MANOS</p>
    <p>. VERSATIL PERO DEJA DUDAS EN DEFENSA</p>
    <p>. BUEN REBOTERO EN EL TABLERO PROPIO</p>
    <p>. VALOR: UNDRAFTED</p>
  `,

  "DILLON MITCHELL": `
    <h3>SCOUTING REPORT</h3>
    <p>. SOLIDA ALTURA PARA 3/4; FALTA DE KG</p>
    <p>. BUEN ATLETA; VELOZ, AGIL, CON SALTO</p>
    <p>. APORTE NULO COMO ANOTADOR</p>
    <p>. UN TRIPLE EN +1000 MIN. EN LA 25-26</p>
    <p>. VELOZ PERO LIMITADO PARA CREAR</p>
    <p>. POR DEBAJO DEL 50% EN LIBRES</p>
    <p>. BUEN PASADOR; 3 ASIS POR CADA TOV</p>
    <p>. GRAN DEFENSOR; DEFIENDE 1 A 4</p>
    <p>. DEFENSA PERIMETRAL > INTERIOR</p>
    <p>. BUENA SUMA DE REBOTES Y ROBOS</p>
    <p>. VALOR: 2° RONDA/UNDRAFTED</p>
  `,

  "DONOVAN ATWELL": `
    <h3>SCOUTING REPORT</h3>
    <p>. BUENA ALTURA PARA ESCOLTA</p>
    <p>. SIN GRAN POTENCIA O EXPLOSION</p>
    <p>. TRIPLERO LETAL EN CATCH AND SHOOT </p>
    <p>. 45.8 3P% EN +8 INTENTOS</p>
    <p>. MECANICA RAPIDA; ALCANCE NBA</p>
    <p>. SIN APORTE EN EL RESTO DEL ATAQUE</p>
    <p>. NO CREA TIROS; NO PISA LA PINTURA</p>
    <p>. MUY BUEN DEFENSOR VS. GUARDS</p>
    <p>. SIN POTENCIA PARA ALEROS FUERTES</p>
    <p>. MUY MAL REBOTERO</p>
    <p>. VALOR: 2° RONDA</p>
  `,

  "OTEGA OWEH": `
    <h3>SCOUTING REPORT</h3>
    <p>. ALTURA IDEAL PARA ESCOLTA</p>
    <p>. MUY BUEN ATLETA; VELOCIDAD+SALTO</p>
    <p>. EXPLOSIVO PARA ATACAR EL ARO </p>
    <p>. UN RAYO EN TRANSICION</p>
    <p>. MAL TIRADOR; MALA MECANICA</p>
    <p>. APENAS SUPERA EL 70% EN LIBRES</p>
    <p>. MUY POCO PASE; SOLO MIRA EL ARO</p>
    <p>. JUGADOR DE IMPACTO EN DEFENSA</p>
    <p>. ESPECIALISTA EN ROBOS</p>
    <p>. BUEN REBOTERO DEFENSIVO</p>
    <p>. VALOR: 2° RONDA</p>
  `,

  "RYAN CONWELL": `
    <h3>SCOUTING REPORT</h3>
    <p>. SIN GRAN ALTURA PERO FUERTE</p>
    <p>. SOLIDO DESDE LO ATLETICO</p>
    <p>. ESPECIALISTA EN TIRO DE TRES</p>
    <p>. BUEN TIRO TRAS DRIBLE; STEPBACKS</p>
    <p>. MENTALIDAD DE SHOOTER</p>
    <p>. NO DESTACA A LA HORA DE PENETRAR</p>
    <p>. ALTURA DE BASE, JUEGO DE ESCOLTA</p>
    <p>. PASA MUY POCO EL BALON</p>
    <p>. LIMITADO POR ALTURA EN DEFENSA</p>
    <p>. GRAN REBOTERO PARA SU ALTURA</p>
    <p>. VALOR: 2° RONDA/UNDRAFTED</p>
  `,

  "MILOS UZAN": `
    <h3>SCOUTING REPORT</h3>
    <p>. BUENA ALTURA; FALTA DE KILOS</p>
    <p>. NO DESTACA DESDE LO ATLETICO</p>
    <p>. CORRECTO TIRO DE TRES PUNTOS</p>
    <p>. CUANDO ATACA USA LA FLOTADORA</p>
    <p>. MUY MAL DEFINIDOR EN LA PINTURA</p>
    <p>. ESCAPA AL CONTACTO; FALTA POTENCIA</p>
    <p>. PASADOR INTELIGENTE, SIN ERRORES</p>
    <p>. GRAN RELACION DE ASIS VS. TOV</p>
    <p>. ALGO LIVIANO EN DEFENSA</p>
    <p>. NO VA AL REBOTE; POCOS ROBOS</p>
    <p>. VALOR: UNDRAFTED</p>
  `,

  "EMANUEL SHARP": `
    <h3>SCOUTING REPORT</h3>
    <p>. MUY BAJO PARA ESCOLTA</p>
    <p>. FUERTE PERO NO ATLETICO</p>
    <p>. ESPECIALISTA EN TRIPLES</p>
    <p>. MECANICA RARA PERO VELOZ Y EFICAZ</p>
    <p>. CAPAZ DE ANOTAR DE 8+ METROS</p>
    <p>. TOQUE PURO; 90% EN TIROS LIBRES</p>
    <p>. MUY POCA CREACION O PASE</p>
    <p>. SIN EXPLOSION/TAMAÑO PARA DEFINIR</p>
    <p>. DEFENSOR LIMITADO PERO FISICO</p>
    <p>. BUENA MARCA SIN BALON; ESFUERZO</p>
    <p>. VALOR: UNDRAFTED</p>
  `,

  "BRYCE HOPKINS": `
    <h3>SCOUTING REPORT</h3>
    <p>. ALTURA, POTENCIA, BRAZOS LARGOS</p>
    <p>. MAS FUERTE QUE SUPER ATLETICO</p>
    <p>. TRIPLERO IRREGULAR; 32% EN 5 AÑOS</p>
    <p>. ALREDEDOR DEL 70% EN LIBRES</p>
    <p>. ATACA POR FISICO Y FORTALEZA</p>
    <p>. SIN GRAN TALENTO CON LA BOLA</p>
    <p>. APENAS PROMEDIO COMO PASADOR</p>
    <p>. EXCELENTE JUGADOR DEFENSIVO</p>
    <p>. MUY FISICO; BUENA MARCA PERIMETRAL</p>
    <p>. GRAN REBOTERO; MUCHOS ROBOS</p>
    <p>. VALOR: UNDRAFTED</p>
  `,

  "ISAIAH EVANS": `
    <h3>SCOUTING REPORT</h3>
    <p>. EXCELENTE ALTURA PARA ESCOLTA</p>
    <p>. BUEN ATLETA PERO MUY FLACO</p>
    <p>. TRIPLERO LETAL; GRAN MECANICA </p>
    <p>. ANOTA EN MOVIMIENTO; ALCANCE NBA</p>
    <p>. DESTELLOS COMO DEFINIDOR</p>
    <p>. BUENOS CORTES SIN BALON</p>
    <p>. LIMITADO POR FALTA DE KILOS</p>
    <p>. POCO PASE; FUERZA MALOS TIROS</p>
    <p>. BUENA ENERGIA PARA DEFENDER</p>
    <p>. DOMINADO POR RIVALES FUERTES</p>
    <p>. VALOR: FINAL 1° RONDA/2° RONDA</p>
  `,

  "KEBA KEITA": `
    <h3>SCOUTING REPORT</h3>
    <p>. PIVOT MUY FUERTE Y ATLETICO</p>
    <p>. EXPLOSIVO COMO DEFINIDOR</p>
    <p>. ANOTA DE ALLEY-OOPS Y PUTBACKS</p>
    <p>. BAJISIMO NIVEL TECNICO CON EL BALON</p>
    <p>. SIN TIRO DE MEDIA O LARGA DISTANCIA</p>
    <p>. NO APORTA COMO PASADOR O CREADOR</p>
    <p>. DEFENSOR FISICO Y COMPETITIVO</p>
    <p>. BUEN APORTE EN REBOTES Y TAPONES</p>
    <p>. PIERDE ANTE PIVOTS MAS ALTOS</p>
    <p>. SIN GRAN AGILIDAD PERIMETRAL</p>
    <p>. VALOR: UNDRAFTED</p>
  `,

};

const listsContainer = document.getElementById("player-lists");
const bottomLeft = document.getElementById("bottom-left");
const bottomRight = document.getElementById("bottom-right");
const scoutTextEl = document.getElementById("scout-text");

const columns = [[], [], []];
players.forEach(p => columns[p.column].push(p));

const headerGradients = [
  "linear-gradient(90deg,#ffd700,#ffec7a)",
  "linear-gradient(90deg,#9b59ff,#cda3ff)",
  "linear-gradient(90deg,#00f7ff,#7ef3ff)"
];

const columnTitles = ["ON-BALL", "OFF-BALL", "BIGS"];

columns.forEach((col, idx) => {
  const c = document.createElement('div');
  c.className = 'column';

const h = document.createElement('div');
h.className = 'column-header';
h.style.background = headerGradients[idx];
c.appendChild(h);

// 🔥 NUEVO: título
const title = document.createElement('div');
title.className = 'column-title';
title.textContent = columnTitles[idx];
c.appendChild(title);
const bottomBar = document.createElement('div');
bottomBar.className = 'column-header';
bottomBar.style.background = headerGradients[idx];
c.appendChild(bottomBar);

  col.forEach(pl => {
const el = document.createElement('div');
el.className = 'player-name';
el.textContent = formatName(pl.name);

el.dataset.col = idx;
el.dataset.row = col.indexOf(pl);

    if (idx === 0) el.style.color = '#ffd700';
    if (idx === 1) el.style.color = '#cda3ff';
    if (idx === 2) el.style.color = '#7ef3ff';

    el.onclick = () => selectPlayer(pl, el);
    c.appendChild(el);
  });

  listsContainer.appendChild(c);
});

function formatName(name) {
  return name
    .split(" ")
    .map(word => {
      // 🔥 si ya viene en mayúsculas y es corto → lo dejamos
      if (word === word.toUpperCase() && word.length <= 2) {
        return word;
      }

      const lower = word.toLowerCase();
      return lower.charAt(0).toUpperCase() + lower.slice(1);
    })
    .join(" ");
}

function selectPlayer(player, el) {
  currentPlayer = player;
currentColIndex = parseInt(el.dataset.col);
currentRowIndex = parseInt(el.dataset.row);
  scoutMode = false;
  scoutTextEl.textContent = "SCOUT";
updateRatingsTitle();

  // 🔥 cortar escritura si venía de scout
  typingTimeouts.forEach(t => clearTimeout(t));
  typingTimeouts = [];

  document.querySelectorAll('.player-name')
    .forEach(e => e.classList.remove('selected'));

  el.classList.add('selected');

ratingsPage = 0;

bottomLeft.innerHTML = `
  <div class="portrait-placeholder">
    <img src="${player.img}" alt="${player.name}">
  </div>

  <div class="stat-box">
    <div class="ratings-title" id="ratings-title">RATINGS</div>

    <div class="ratings-page" data-page="0">
      ${renderStats(player.stats)}
    </div>

    <div class="ratings-page" data-page="1" style="display:none;">
      <div class="alt-page">
        ${renderStats(player.shotStats || {})}
      </div>
    </div>

    <div class="ratings-page" data-page="2" style="display:none;">
      <div class="alt-page">
        ${renderStats(player.defenseStats || {})}
      </div>
    </div>

<div class="ratings-page" data-page="3" style="display:none;">
  <div class="alt-page">
    <div class="comparison-box">
      <div id="comp-result">-</div>
      <div id="comp-btn">COMP</div>
    </div>
  </div>
</div>

    <div class="ratings-arrow left" onclick="prevRatingsPage()">◀</div>
    <div class="ratings-arrow right" onclick="nextRatingsPage()">▶</div>
  </div>
`;

// 👇 PEGAR ACÁ
setTimeout(() => {
  const btn = document.getElementById("comp-btn");
  if (btn) {
    btn.onclick = startComparison;
  }
}, 0);

  renderNormalInfo(player);
}

function renderNormalInfo(player) {
  bottomRight.innerHTML = `
    <h3></h3>
    <p>NOMBRE: ${player.name}</p>
    <p>ALTURA: ${player.height}</p>
    <p>NACIONALIDAD: ${player.country}</p>
    <p>POSICION: ${player.position}</p>
    <p>EQUIPO: ${player.team}</p>
    <p>EDAD: ${player.age}</p>
    <p>ATAQUE ${player.ataque}</p>
    <p>DEFENSA ${player.defensa}</p>
  `;
}

function renderStats(s) {
  return `
    <div class="stats-grid">
      <div class="stats-column">
        ${Object.entries(s).map(([key, val]) => `
          <div class="stat-row">
            <div class="stat-label">${key.toUpperCase()}:</div>
            <div class="stat-bars">${renderSegments(val)}</div>
          </div>
        `).join('')}
      </div>
    </div>
  `;
}



function renderSegments(v) {
  return `
    <div class="stat-bar">
      <div class="stat-bar-fill" style="width:${v}%"></div>
    </div>
  `;
}

const randomNames = players.map(p => p.name);
let compInterval = null;

// 🔥 AUDIO
const compSound = new Audio("Comp.wav");
const scoutSound = new Audio("Scout.wav");
const clickSound = new Audio("Click.wav");

function playClickSound() {
  clickSound.currentTime = 0;
  clickSound.play();
}

function startComparison() {
  const resultEl = document.getElementById("comp-result");
  if (!resultEl || !currentPlayer) return;

  // 🔥 reproducir sonido
  compSound.currentTime = 0;
compSound.volume = 0.3
  compSound.play();

  // limpiar si ya estaba corriendo
  if (compInterval) clearInterval(compInterval);

  let elapsed = 0;

  compInterval = setInterval(() => {
    const random = randomNames[Math.floor(Math.random() * randomNames.length)];
    resultEl.textContent = random;

    elapsed += 100;

    if (elapsed >= 1800) {
      clearInterval(compInterval);
      resultEl.textContent = currentPlayer.comp || "-";
    }

  }, 100);
}

function nextRatingsPage() {
  playClickSound();

  const pages = document.querySelectorAll('.ratings-page');

  pages[ratingsPage].style.display = 'none';

  ratingsPage = (ratingsPage + 1) % pages.length;

  pages[ratingsPage].style.display = 'block';

  updateRatingsTitle(); // 👈 clave
}

function prevRatingsPage() {
  playClickSound();

  const pages = document.querySelectorAll('.ratings-page');

  pages[ratingsPage].style.display = 'none';

  ratingsPage = (ratingsPage - 1 + pages.length) % pages.length;

  pages[ratingsPage].style.display = 'block';

  updateRatingsTitle(); // 👈 clave
}

function updateSelection(colIndex, rowIndex) {
  const columnEls = document.querySelectorAll('.column');
  const targetColumn = columnEls[colIndex];

  const playersEls = targetColumn.querySelectorAll('.player-name');
  const targetEl = playersEls[rowIndex];

  if (targetEl) {
    targetEl.click();

// 🔥 NUEVO: hacer scroll dentro de la columna
const container = targetColumn;

const offsetTop = targetEl.offsetTop;
const offsetBottom = offsetTop + targetEl.offsetHeight;

const visibleTop = container.scrollTop;
const visibleBottom = visibleTop + container.clientHeight;

// 🔥 SI ES EL PRIMERO → mostrar todo arriba (incluye título)
if (rowIndex === 0) {
  container.scrollTop = 0;
  return;
}

// si está arriba del visible → subir
if (offsetTop < visibleTop) {
  container.scrollTop = offsetTop - 40;
}

// si está abajo del visible → bajar
if (offsetBottom > visibleBottom) {
  container.scrollTop = offsetBottom - container.clientHeight + 10;
}
  }
}

function updateRatingsTitle() {
  const title = document.getElementById('ratings-title');
  if (!title) return;

const titles = ["RATINGS", "ATAQUE", "DEFENSA", "COMPARACION"];

  title.textContent = titles[ratingsPage] || "RATINGS";
}

window.addEventListener('DOMContentLoaded', () => {
  const f = document.querySelector('.player-name');
  if (f) f.click();
});

document.getElementById('scout-btn').onclick = () => {
  if (!currentPlayer) return;

  scoutSound.currentTime = 0;
scoutSound.volume = 0.3
  scoutSound.play();

  scoutMode = !scoutMode;

  if (scoutMode) {
    typeWriterHTML(
      bottomRight,
      SCOUT_DATA[currentPlayer.name] || SCOUT_DATA.default,
      12
    );
    scoutTextEl.textContent = "DATOS";
  } else {
    // 🔥 cortar escritura al volver a stats
    typingTimeouts.forEach(t => clearTimeout(t));
    typingTimeouts = [];

    renderNormalInfo(currentPlayer);
    scoutTextEl.textContent = "SCOUT";
  }
};

function typeWriterHTML(element, html, speed = 15) {
  // 🔥 limpiar timeouts anteriores
  typingTimeouts.forEach(t => clearTimeout(t));
  typingTimeouts = [];

  element.innerHTML = "";

  const temp = document.createElement("div");
  temp.innerHTML = html;

  const nodes = temp.querySelectorAll("h3, p");

  let currentNode = 0;

  function typeNode() {
    if (currentNode >= nodes.length) return;

    const originalNode = nodes[currentNode];
    const newNode = document.createElement(originalNode.tagName);

    element.appendChild(newNode);

    const text = originalNode.textContent;
    let i = 0;

    function typeChar() {
      if (i < text.length) {
        newNode.textContent += text.charAt(i);
        i++;

        const t = setTimeout(typeChar, speed);
        typingTimeouts.push(t);

      } else {
        currentNode++;

        const t = setTimeout(typeNode, 120);
        typingTimeouts.push(t);
      }
    }

    typeChar();
  }

  typeNode();
}

document.addEventListener('keydown', (e) => {
  if (!currentPlayer) return;

  let newCol = currentColIndex;
  let newRow = currentRowIndex;

  switch (e.key) {
    case 'ArrowDown':
      e.preventDefault();
      if (newRow < columns[newCol].length - 1) {
        newRow++;
      }
      break;

    case 'ArrowUp':
      e.preventDefault();
      if (newRow > 0) {
        newRow--;
      }
      break;

    case 'ArrowRight':
      e.preventDefault();
      newCol = (newCol + 1) % columns.length;
      newRow = Math.min(newRow, columns[newCol].length - 1);
      break;

    case 'ArrowLeft':
      e.preventDefault();
      newCol = (newCol - 1 + columns.length) % columns.length;
      newRow = Math.min(newRow, columns[newCol].length - 1);
      break;

    default:
      return;
  }

  updateSelection(newCol, newRow);
});
